version: '3'
services:
  app:
    build: .
    container_name: my_python_os
    environment:
      - PYTHON_ENV=production
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python3 src/main.py
